// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace CommonAnnotatedSecurityKeys;

internal enum CaskVersion : byte
{
    /// <summary>
    /// Specifies version 1.0.0 of CASK.
    /// </summary>
    OneZeroZero,

    Reserved = 0xfe,
}

internal enum KeyKind : byte
{
    /// <summary>
    /// Specifies a 256-bit primary API or other security key. The enum
    /// value '0' comprises the base64 index that maps to character 'A'.
    /// </summary>
    Key256Bit = 0, // Base64 index 0 == 'A'

    /// <summary>
    /// Specifies a CASK hashed signature that incorporates a Keyed Hash
    /// Message Authenticode of a derivation input generated by SHA-256
    /// (HMAC-SHA-256) along with other CASK data such as the generated
    /// C3ID of the CASK key used to initialize the HMAC instance.
    /// </summary>
    Hash256Bit = 7,

    /// <summary>
    /// Specifies a CASK hashed signature that incorporates a Keyed Hash
    /// Message Authenticode of a derivation input generated by SHA-384
    /// (HMAC-SHA-384) along with other CASK data such as the generated
    /// C3ID of the CASK key used to initialize the HMAC instance.
    /// </summary>
    Hash384Bit = 8,

    Reserved = (Key256Bit | Hash256Bit | Hash384Bit) ^ 0xff,
}
