name: Validate
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Show dotnet info
      run: dotnet --info

    - name: Restore
      run: dotnet restore src

    - name: Build
      run: dotnet build src -c Release --no-restore

    - name: Test
      run: dotnet test src -c Release --no-build
