name: Validate
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        configuration: [debug, release]
    runs-on: ${{matrix.os}}
    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup dotnet
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: 9.0.x

    - name: Show dotnet info
      run: dotnet --info

    - name: Restore
      run: dotnet restore src

    - name: Check Formatting
      run: dotnet format --verify-no-changes src --verbosity diagnostic

    - name: Build
      run: dotnet build src -c ${{matrix.configuration}} --no-restore

    - name: Test
      run: dotnet test src -c ${{matrix.configuration}} --no-build
